# Generated by Django 6.0 on 2026-02-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipsy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=10),
        ),
    ]
