# Generated by Django 6.0 on 2026-04-02 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipsy', '0005_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude for location-based delivery', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude for location-based delivery', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_shop',
            field=models.ForeignKey(blank=True, help_text='The closest vendor matching this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.FloatField(blank=True, help_text='Distance from selected shop in km', null=True),
        ),
    ]
