# Generated by Django 6.0 on 2026-04-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipsy', '0006_customuser_latitude_customuser_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pan_document',
            field=models.FileField(blank=True, help_text='PAN Document Upload', null=True, upload_to='vendor_documents/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN Number for Vendors', max_length=20, null=True),
        ),
    ]
