# Generated by Django 6.0 on 2026-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipsy', '0007_customuser_pan_document_customuser_pan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business_name',
            field=models.CharField(blank=True, help_text='Business Name for Vendors', max_length=255, null=True),
        ),
    ]
