# Generated by Django 6.0 on 2026-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipsy', '0008_customuser_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tax_document',
            field=models.FileField(blank=True, help_text='Tax Clearance Certificate Upload', null=True, upload_to='vendor_documents/'),
        ),
    ]
