# Generated by Django 6.0 on 2026-04-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipsy', '0009_customuser_tax_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
