# Generated by Django 6.0 on 2026-04-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipsy', '0012_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Placed', 'Placed'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
