# Generated by Django 6.0 on 2026-04-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipsy', '0017_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
