from django.urls import path
from .views import (
    HomeView, ProductListView, ProductDetailView,
    SignUpView, UserLoginView, UserLogoutView, EmailVerificationView,
    CustomerDashboardView, CustomerProfileUpdateView,
    CartView, AddToCartView, UpdateCartView, RemoveFromCartView,
    CheckoutView, OrderHistoryView, KhaltiPaymentView, KhaltiVerifyView,
    NotificationListView, NotificationDetailView, MarkNotificationAsReadView, 
    MarkAllNotificationsAsReadView, UnreadNotificationCountView,
    CustomerChatView, ChatAPIView,
    submit_feedback,
)
from .admin_views import (
    AdminDashboardView, AdminVendorsView, AdminApproveVendorView, AdminRejectVendorView, AdminRemoveVendorView,
    admin_export_report_pdf,
    AdminProductsView, AdminOrdersView, AdminCustomersView, AdminChangeUserPasswordView,
)
from .vendor_views import (
    VendorDashboardView, VendorOrdersView, VendorUpdateOrderStatusView,
    VendorNewOrdersView, VendorOrdersToDeliverView, VendorDeliveredOrdersView, VendorProductsView,
    vendor_export_report, vendor_export_products_pdf,
    vendor_export_new_orders, vendor_export_orders_to_deliver, vendor_export_delivered_orders,
    ProductCreateView, ProductUpdateView, ProductDeleteView,
    VendorProfileUpdateView, VendorNotificationListView, VendorNotificationDetailView, VendorUnreadNotificationCountView,
    VendorChatListView, VendorChatDetailView
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("verify-email/<uidb64>/<token>/", EmailVerificationView.as_view(), name="verify_email"),

    # Custom Admin URLs
    path("control/dashboard/", AdminDashboardView.as_view(), name="admin_dashboard"),
    path("control/dashboard/export-pdf/", admin_export_report_pdf, name="admin_export_report_pdf"),
    path("control/vendors/", AdminVendorsView.as_view(), name="admin_vendors"),
    path("control/vendors/<int:user_id>/approve/", AdminApproveVendorView.as_view(), name="admin_approve_vendor"),
    path("control/vendors/<int:user_id>/reject/", AdminRejectVendorView.as_view(), name="admin_reject_vendor"),
    path("control/vendors/<int:user_id>/remove/", AdminRemoveVendorView.as_view(), name="admin_remove_vendor"),
    path("control/users/<int:user_id>/change-password/", AdminChangeUserPasswordView.as_view(), name="admin_change_user_password"),
    path("control/products/", AdminProductsView.as_view(), name="admin_products"),
    path("control/orders/", AdminOrdersView.as_view(), name="admin_orders"),
    path("control/customers/", AdminCustomersView.as_view(), name="admin_customers"),
    
    # Vendor URLs
    path("vendor/dashboard/", VendorDashboardView.as_view(), name="vendor_dashboard"),
    path("vendor/export-report/", vendor_export_report, name="vendor_export_report"),
    path("vendor/products/", VendorProductsView.as_view(), name="vendor_products"),
    path("vendor/products/export-pdf/", vendor_export_products_pdf, name="vendor_export_products_pdf"),
    path("vendor/product/add/", ProductCreateView.as_view(), name="add_product"),
    path("vendor/product/<int:pk>/edit/", ProductUpdateView.as_view(), name="edit_product"),
    path("vendor/product/<int:pk>/delete/", ProductDeleteView.as_view(), name="delete_product"),
    path("vendor/orders/", VendorOrdersView.as_view(), name="vendor_orders"),
    path("vendor/orders/new/", VendorNewOrdersView.as_view(), name="vendor_new_orders"),
    path("vendor/orders/new/export-pdf/", vendor_export_new_orders, name="vendor_export_new_orders"),
    path("vendor/orders/to-deliver/", VendorOrdersToDeliverView.as_view(), name="vendor_orders_to_deliver"),
    path("vendor/orders/to-deliver/export-pdf/", vendor_export_orders_to_deliver, name="vendor_export_orders_to_deliver"),
    path("vendor/orders/delivered/", VendorDeliveredOrdersView.as_view(), name="vendor_delivered_orders"),
    path("vendor/orders/delivered/export-pdf/", vendor_export_delivered_orders, name="vendor_export_delivered_orders"),
    path("vendor/orders/<int:order_id>/status/", VendorUpdateOrderStatusView.as_view(), name="vendor_update_order_status"),
    path("vendor/profile/", VendorProfileUpdateView.as_view(), name="vendor_profile"),
    path("vendor/notifications/", VendorNotificationListView.as_view(), name="vendor_notification_list"),
    path("vendor/notifications/<int:pk>/", VendorNotificationDetailView.as_view(), name="vendor_notification_detail"),
    path("vendor/api/notifications/unread-count/", VendorUnreadNotificationCountView.as_view(), name="vendor_unread_notification_count"),
    path("vendor/chats/", VendorChatListView.as_view(), name="vendor_chats"),
    path("vendor/chats/<int:chat_id>/", VendorChatDetailView.as_view(), name="vendor_chat_detail"),
    
    # Customer URLs
    path("shop/", CustomerDashboardView.as_view(), name="customer_dashboard"),
    path("products/", ProductListView.as_view(), name="product_list"),
    path("products/<int:id>/", ProductDetailView.as_view(), name="product_detail"),
    path("cart/add/<int:product_id>/", AddToCartView.as_view(), name="add_to_cart"),
    path("cart/", CartView.as_view(), name="view_cart"),
    path("cart/update/<int:item_id>/", UpdateCartView.as_view(), name="update_cart"),
    path("cart/remove/<int:item_id>/", RemoveFromCartView.as_view(), name="remove_from_cart"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("orders/", OrderHistoryView.as_view(), name="order_history"),
    path("feedback/<int:order_id>/<int:product_id>/", submit_feedback, name="submit_feedback"),
    path("profile/", CustomerProfileUpdateView.as_view(), name="customer_profile"),
    path("payment/khalti/<int:payment_id>/", KhaltiPaymentView.as_view(), name="khalti_payment"),
    path("payment/khalti/verify/", KhaltiVerifyView.as_view(), name="khalti_verify"),
    path("notifications/", NotificationListView.as_view(), name="notification_list"),
    path("notifications/<int:pk>/", NotificationDetailView.as_view(), name="notification_detail"),
    path("api/notifications/<int:notification_id>/mark-as-read/", MarkNotificationAsReadView.as_view(), name="mark_notification_as_read"),
    path("api/notifications/mark-all-read/", MarkAllNotificationsAsReadView.as_view(), name="mark_all_notifications_as_read"),
    path("api/notifications/unread-count/", UnreadNotificationCountView.as_view(), name="unread_notification_count"),
    path("chat/vendor/<int:vendor_id>/", CustomerChatView.as_view(), name="customer_chat"),
    path("api/chat/<int:chat_id>/", ChatAPIView.as_view(), name="chat_api"),
]